title: Opetusjuttuja fyssan laitoksella, jahuu!
url: "https://fystiedekasvatus.github.io"
defaults:
    -
     scope:
         path: ""
     values:
         layout: default
         lang: fi
         base-url: ""
    -
     scope:
         path: "se"
     values:
         lang: se
         base-url: "se/"
    -
     scope:
         path: "en"
     values:
         lang: en
         base-url: "en/"
